import { DOCUMENT_TYPES } from "@/lib/document-types";

export type DocumentFamily = "AVANT_FORMATION" | "PENDANT_FORMATION" | "APRES_FORMATION" | "ADMINISTRATIF" | "FINANCE" | "QUALIOPI";
export type DocumentMaturity = "READY" | "PARTIAL" | "GENERIC";
export type DocumentScope = "LEARNER" | "SESSION" | "COMPANY" | "ANNUAL";

export type DocumentCatalogEntry = {
  type: string;
  label: string;
  family: DocumentFamily;
  description: string;
  maturity: DocumentMaturity;
  recommendedVariables: string[];
  importantVariables: string[];
  optionalVariables: string[];
  contexts: string[];
  bulkGeneratable: boolean;
  scope: DocumentScope;
};

const BASE: Record<string, Omit<DocumentCatalogEntry, "type" | "label">> = {
  PROGRAMME: { family: "AVANT_FORMATION", description: "Programme pédagogique et commercial de l'action.", maturity: "READY", recommendedVariables: ["org_name", "formation_title", "formation_duration_hours", "formation_objectives", "formation_program"], importantVariables: ["formation_title", "formation_program"], optionalVariables: ["formation_modality", "amountText"], contexts: ["organization", "formation"], bulkGeneratable: false, scope: "SESSION" },
  CONVENTION: { family: "AVANT_FORMATION", description: "Convention de formation entre le centre et une entreprise ou financeur.", maturity: "READY", recommendedVariables: ["org_legal_name", "org_nda", "formation_title", "session_date_range", "company_name", "amountText"], importantVariables: ["org_legal_name", "formation_title", "company_name"], optionalVariables: ["funding_organization", "payment_terms"], contexts: ["organization", "formation", "session", "learner", "billing"], bulkGeneratable: false, scope: "COMPANY" },
  CONTRAT_FORMATION: { family: "AVANT_FORMATION", description: "Contrat de formation pour financement individuel.", maturity: "PARTIAL", recommendedVariables: ["org_legal_name", "learner_name", "formation_title", "session_date_range", "amountText"], importantVariables: ["learner_name", "formation_title"], optionalVariables: ["payment_terms"], contexts: ["organization", "formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  LIVRET_ACCUEIL: { family: "AVANT_FORMATION", description: "Livret d'accueil de l'apprenant.", maturity: "GENERIC", recommendedVariables: ["org_name", "org_email", "org_phone", "formation_title"], importantVariables: ["org_name"], optionalVariables: ["satisfaction_survey_url"], contexts: ["organization", "formation"], bulkGeneratable: false, scope: "SESSION" },
  TEST_POSITIONNEMENT: { family: "AVANT_FORMATION", description: "Test initial de positionnement.", maturity: "GENERIC", recommendedVariables: ["learner_name", "formation_title"], importantVariables: ["learner_name", "formation_title"], optionalVariables: ["generatedAt"], contexts: ["formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  CONVOCATION: { family: "AVANT_FORMATION", description: "Convocation apprenant à une session.", maturity: "READY", recommendedVariables: ["org_name", "learner_name", "formation_title", "session_date_range", "trainer_name", "session_location"], importantVariables: ["learner_name", "formation_title", "session_date_range"], optionalVariables: ["room_name", "org_phone"], contexts: ["organization", "formation", "session", "learner", "trainer", "room"], bulkGeneratable: true, scope: "LEARNER" },
  EMARGEMENT: { family: "PENDANT_FORMATION", description: "Feuille d'émargement de session.", maturity: "READY", recommendedVariables: ["org_name", "formation_title", "session_date_range", "trainer_name"], importantVariables: ["formation_title", "session_date_range"], optionalVariables: ["room_name"], contexts: ["organization", "formation", "session", "trainer", "room"], bulkGeneratable: false, scope: "SESSION" },
  SUPPORT_COURS: { family: "PENDANT_FORMATION", description: "Support pédagogique remis aux apprenants.", maturity: "GENERIC", recommendedVariables: ["formation_title", "formation_objectives"], importantVariables: ["formation_title"], optionalVariables: ["formation_program"], contexts: ["formation"], bulkGeneratable: false, scope: "SESSION" },
  QUESTIONNAIRE_SUIVI: { family: "PENDANT_FORMATION", description: "Questionnaire de suivi à mi-parcours.", maturity: "GENERIC", recommendedVariables: ["learner_name", "formation_title", "session_date_range"], importantVariables: ["learner_name", "formation_title"], optionalVariables: [], contexts: ["formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  ATTESTATION: { family: "APRES_FORMATION", description: "Attestation de fin de formation.", maturity: "READY", recommendedVariables: ["org_legal_name", "learner_name", "formation_title", "session_date_range", "attendance_hours"], importantVariables: ["learner_name", "formation_title"], optionalVariables: ["attendance_rate"], contexts: ["organization", "formation", "session", "learner", "certification"], bulkGeneratable: true, scope: "LEARNER" },
  CERTIFICAT: { family: "APRES_FORMATION", description: "Certificat de réalisation.", maturity: "READY", recommendedVariables: ["org_legal_name", "learner_name", "formation_title", "session_date_range", "attendance_hours"], importantVariables: ["learner_name", "formation_title"], optionalVariables: ["certificate_date"], contexts: ["organization", "formation", "session", "learner", "certification"], bulkGeneratable: true, scope: "LEARNER" },
  ATTESTATION_PRESENCE: { family: "APRES_FORMATION", description: "Attestation de présence ou d'assiduité.", maturity: "PARTIAL", recommendedVariables: ["learner_name", "formation_title", "attendance_hours", "attendance_rate"], importantVariables: ["learner_name", "formation_title"], optionalVariables: ["session_date_range"], contexts: ["session", "learner", "certification"], bulkGeneratable: true, scope: "LEARNER" },
  QUESTIONNAIRE_SATISFACTION: { family: "APRES_FORMATION", description: "Questionnaire de satisfaction générique.", maturity: "GENERIC", recommendedVariables: ["learner_name", "formation_title", "satisfaction_survey_url"], importantVariables: ["formation_title"], optionalVariables: ["session_date_range"], contexts: ["formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  ENQUETE_SATISFACTION_CHAUD: { family: "APRES_FORMATION", description: "Enquête satisfaction à chaud.", maturity: "GENERIC", recommendedVariables: ["learner_name", "formation_title", "satisfaction_survey_url"], importantVariables: ["formation_title"], optionalVariables: [], contexts: ["formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  ENQUETE_SATISFACTION_FROID: { family: "APRES_FORMATION", description: "Enquête satisfaction à froid.", maturity: "GENERIC", recommendedVariables: ["learner_name", "formation_title", "satisfaction_survey_url"], importantVariables: ["formation_title"], optionalVariables: [], contexts: ["formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  SYNTHESE_SATISFACTION: { family: "QUALIOPI", description: "Synthèse des retours de satisfaction.", maturity: "GENERIC", recommendedVariables: ["formation_title", "session_date_range"], importantVariables: ["formation_title"], optionalVariables: ["satisfaction_survey_url"], contexts: ["formation", "session"], bulkGeneratable: false, scope: "SESSION" },
  DIPLOME_TITRE: { family: "APRES_FORMATION", description: "Diplôme ou titre certifiant.", maturity: "PARTIAL", recommendedVariables: ["learner_name", "formation_title", "certificate_date"], importantVariables: ["learner_name", "formation_title"], optionalVariables: [], contexts: ["learner", "formation", "certification"], bulkGeneratable: true, scope: "LEARNER" },
  DEVIS: { family: "FINANCE", description: "Devis commercial simple.", maturity: "READY", recommendedVariables: ["org_legal_name", "quote_number", "company_name", "formation_title", "amountText"], importantVariables: ["company_name", "formation_title", "amountText"], optionalVariables: ["payment_terms"], contexts: ["organization", "formation", "session", "billing"], bulkGeneratable: false, scope: "COMPANY" },
  FACTURE: { family: "FINANCE", description: "Facture simple.", maturity: "PARTIAL", recommendedVariables: ["org_legal_name", "invoice_number", "company_name", "formation_title", "amountText"], importantVariables: ["invoice_number", "company_name", "amountText"], optionalVariables: ["payment_terms"], contexts: ["organization", "formation", "session", "billing"], bulkGeneratable: false, scope: "COMPANY" },
  BPF: { family: "ADMINISTRATIF", description: "Bilan pédagogique et financier annuel.", maturity: "GENERIC", recommendedVariables: ["org_legal_name", "org_siret", "org_nda"], importantVariables: ["org_legal_name"], optionalVariables: [], contexts: ["organization", "annualReport"], bulkGeneratable: false, scope: "ANNUAL" },
  PROGRAMME_FORMATION: { family: "AVANT_FORMATION", description: "Programme de formation détaillé.", maturity: "READY", recommendedVariables: ["centre_nom", "formation_titre", "formation_objectifs", "formation_programme"], importantVariables: ["formation_titre", "formation_programme"], optionalVariables: ["formation_tarif"], contexts: ["organization", "formation"], bulkGeneratable: false, scope: "SESSION" },
  FICHE_FORMATION_PUBLIQUE: { family: "AVANT_FORMATION", description: "Fiche publique de présentation formation.", maturity: "READY", recommendedVariables: ["centre_nom", "formation_titre", "formation_resume", "formation_public"], importantVariables: ["formation_titre"], optionalVariables: ["contact_url"], contexts: ["organization", "formation"], bulkGeneratable: false, scope: "SESSION" },
  OBJECTIFS_PEDAGOGIQUES: { family: "AVANT_FORMATION", description: "Objectifs pédagogiques de la formation.", maturity: "READY", recommendedVariables: ["formation_titre", "formation_objectifs", "competences_visees"], importantVariables: ["formation_titre"], optionalVariables: [], contexts: ["formation"], bulkGeneratable: false, scope: "SESSION" },
  PREREQUIS_POSITIONNEMENT: { family: "AVANT_FORMATION", description: "Pré-requis et positionnement initial.", maturity: "READY", recommendedVariables: ["formation_titre", "formation_prerequis", "test_positionnement_resultat"], importantVariables: ["formation_titre"], optionalVariables: ["adaptations_recommandees"], contexts: ["formation", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  DEROULE_PEDAGOGIQUE_MODULE: { family: "AVANT_FORMATION", description: "Déroulé pédagogique par module.", maturity: "READY", recommendedVariables: ["formation_titre", "modules_liste", "module_titre"], importantVariables: ["formation_titre"], optionalVariables: ["module_objectifs"], contexts: ["formation", "modules"], bulkGeneratable: false, scope: "SESSION" },
  GRILLE_FORMATION_COMPETENCES: { family: "AVANT_FORMATION", description: "Grille de correspondance formation-compétences.", maturity: "READY", recommendedVariables: ["formation_titre", "competences_liste"], importantVariables: ["formation_titre"], optionalVariables: [], contexts: ["formation"], bulkGeneratable: false, scope: "SESSION" },
  PLAN_INDIVIDUEL_FORMATION: { family: "AVANT_FORMATION", description: "Plan individuel de formation.", maturity: "READY", recommendedVariables: ["apprenant_nom", "formation_titre", "objectifs_individuels"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["adaptations"], contexts: ["formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  CONVENTION_FORMATION_ENTREPRISE: { family: "AVANT_FORMATION", description: "Convention de formation entreprise.", maturity: "READY", recommendedVariables: ["centre_nom", "client_entreprise", "formation_titre", "prix_total"], importantVariables: ["client_entreprise", "formation_titre"], optionalVariables: ["conditions_paiement"], contexts: ["organization", "formation", "session", "billing"], bulkGeneratable: false, scope: "COMPANY" },
  CONTRAT_FORMATION_PARTICULIER: { family: "AVANT_FORMATION", description: "Contrat de formation particulier.", maturity: "READY", recommendedVariables: ["centre_nom", "apprenant_nom", "formation_titre", "prix_total"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["conditions_retractation"], contexts: ["organization", "formation", "session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  DEVIS_FORMATION: { family: "FINANCE", description: "Devis de formation.", maturity: "READY", recommendedVariables: ["centre_nom", "client_nom", "formation_titre", "prix_total"], importantVariables: ["client_nom", "formation_titre", "prix_total"], optionalVariables: ["validite_devis"], contexts: ["organization", "formation", "billing"], bulkGeneratable: false, scope: "COMPANY" },
  BON_DE_COMMANDE: { family: "FINANCE", description: "Bon de commande formation.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "client_nom", "formation_titre", "prix_total"], importantVariables: ["client_nom", "formation_titre"], optionalVariables: ["commande_numero"], contexts: ["organization", "formation", "billing"], bulkGeneratable: false, scope: "COMPANY" },
  CGV_B2B: { family: "ADMINISTRATIF", description: "Conditions générales de vente B2B.", maturity: "GENERIC", recommendedVariables: ["centre_nom", "conditions_paiement"], importantVariables: ["centre_nom"], optionalVariables: ["juridiction"], contexts: ["organization"], bulkGeneratable: false, scope: "COMPANY" },
  CGV_B2C: { family: "ADMINISTRATIF", description: "Conditions générales de vente B2C.", maturity: "GENERIC", recommendedVariables: ["centre_nom", "conditions_retractation"], importantVariables: ["centre_nom"], optionalVariables: ["delai_retractation"], contexts: ["organization"], bulkGeneratable: false, scope: "LEARNER" },
  CONVOCATION_APPRENANT: { family: "AVANT_FORMATION", description: "Convocation apprenant.", maturity: "READY", recommendedVariables: ["apprenant_nom", "formation_titre", "session_dates", "session_lieu"], importantVariables: ["apprenant_nom", "formation_titre", "session_dates"], optionalVariables: ["formateur_nom"], contexts: ["session", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  CONVOCATION_FORMATEUR: { family: "AVANT_FORMATION", description: "Convocation formateur.", maturity: "READY", recommendedVariables: ["formateur_nom", "formation_titre", "session_dates"], importantVariables: ["formateur_nom", "formation_titre"], optionalVariables: ["session_lieu"], contexts: ["session", "trainer"], bulkGeneratable: false, scope: "SESSION" },
  REGLEMENT_INTERIEUR: { family: "ADMINISTRATIF", description: "Règlement intérieur.", maturity: "GENERIC", recommendedVariables: ["centre_nom", "reglement_interieur"], importantVariables: ["centre_nom"], optionalVariables: ["regles_assiduite"], contexts: ["organization"], bulkGeneratable: false, scope: "SESSION" },
  FEUILLE_EMARGEMENT: { family: "PENDANT_FORMATION", description: "Feuille d'émargement de session.", maturity: "READY", recommendedVariables: ["centre_nom", "formation_titre", "session_dates", "apprenants_liste"], importantVariables: ["formation_titre", "session_dates"], optionalVariables: ["signature_matin"], contexts: ["session", "learners"], bulkGeneratable: false, scope: "SESSION" },
  PLANNING_SESSION: { family: "PENDANT_FORMATION", description: "Planning de session.", maturity: "READY", recommendedVariables: ["centre_nom", "formation_titre", "session_dates", "horaires"], importantVariables: ["formation_titre", "session_dates"], optionalVariables: ["modules_liste"], contexts: ["session", "formation"], bulkGeneratable: false, scope: "SESSION" },
  PLANNING_FORMATEUR: { family: "PENDANT_FORMATION", description: "Planning formateur.", maturity: "READY", recommendedVariables: ["formateur_nom", "periode", "sessions_liste"], importantVariables: ["formateur_nom"], optionalVariables: ["contraintes_formateur"], contexts: ["trainer", "planning"], bulkGeneratable: false, scope: "SESSION" },
  ORDRE_MISSION_FORMATEUR: { family: "PENDANT_FORMATION", description: "Ordre de mission formateur.", maturity: "READY", recommendedVariables: ["formateur_nom", "formation_titre", "session_dates"], importantVariables: ["formateur_nom", "formation_titre"], optionalVariables: ["conditions_intervention"], contexts: ["session", "trainer"], bulkGeneratable: false, scope: "SESSION" },
  FICHE_INTERVENTION_FORMATEUR: { family: "PENDANT_FORMATION", description: "Fiche d'intervention formateur.", maturity: "READY", recommendedVariables: ["formateur_nom", "formation_titre", "module_titre"], importantVariables: ["formateur_nom", "formation_titre"], optionalVariables: ["objectifs_seance"], contexts: ["session", "trainer", "module"], bulkGeneratable: false, scope: "SESSION" },
  RELEVE_ASSIDUITE: { family: "APRES_FORMATION", description: "Relevé d'assiduité.", maturity: "PARTIAL", recommendedVariables: ["apprenant_nom", "formation_titre", "heures_prevues", "heures_realisees"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["absence_retard"], contexts: ["session", "learner", "attendance"], bulkGeneratable: true, scope: "LEARNER" },
  FICHE_INCIDENT_SESSION: { family: "QUALIOPI", description: "Fiche incident session.", maturity: "GENERIC", recommendedVariables: ["formation_titre", "session_dates", "description_incident"], importantVariables: ["description_incident"], optionalVariables: ["actions_menees"], contexts: ["session", "quality"], bulkGeneratable: false, scope: "SESSION" },
  DEMANDE_MODIFICATION_PLANNING: { family: "PENDANT_FORMATION", description: "Demande de modification planning.", maturity: "GENERIC", recommendedVariables: ["formation_titre", "session_date_initiale", "motif"], importantVariables: ["motif"], optionalVariables: ["nouvelle_date_proposee"], contexts: ["session", "planning"], bulkGeneratable: false, scope: "SESSION" },
  SYNTHESE_DISPONIBILITES_FORMATEURS: { family: "PENDANT_FORMATION", description: "Synthèse disponibilités formateurs.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "periode", "disponibilites_liste"], importantVariables: ["periode"], optionalVariables: ["indisponibilites_liste"], contexts: ["trainer", "planning"], bulkGeneratable: false, scope: "SESSION" },
  FICHE_APPRENANT: { family: "ADMINISTRATIF", description: "Fiche apprenant.", maturity: "READY", recommendedVariables: ["apprenant_nom", "apprenant_email", "formation_titre"], importantVariables: ["apprenant_nom"], optionalVariables: ["notes_suivi"], contexts: ["learner"], bulkGeneratable: true, scope: "LEARNER" },
  GRILLE_EVALUATION_INITIALE: { family: "AVANT_FORMATION", description: "Grille d'évaluation initiale.", maturity: "GENERIC", recommendedVariables: ["apprenant_nom", "formation_titre", "niveau_initial"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["competences_liste"], contexts: ["learner", "assessment"], bulkGeneratable: true, scope: "LEARNER" },
  GRILLE_EVALUATION_CONTINUE: { family: "PENDANT_FORMATION", description: "Grille d'évaluation continue.", maturity: "GENERIC", recommendedVariables: ["apprenant_nom", "formation_titre", "competences_evaluees"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["niveau_atteint"], contexts: ["learner", "assessment"], bulkGeneratable: true, scope: "LEARNER" },
  COMPTE_RENDU_PROGRESSION: { family: "PENDANT_FORMATION", description: "Compte rendu progression.", maturity: "GENERIC", recommendedVariables: ["apprenant_nom", "formation_titre", "progression"], importantVariables: ["apprenant_nom"], optionalVariables: ["points_forts"], contexts: ["learner", "assessment"], bulkGeneratable: true, scope: "LEARNER" },
  PLAN_ACCOMPAGNEMENT_INDIVIDUALISE: { family: "PENDANT_FORMATION", description: "Plan d'accompagnement individualisé.", maturity: "GENERIC", recommendedVariables: ["apprenant_nom", "objectifs_individuels", "suivi_prevu"], importantVariables: ["apprenant_nom"], optionalVariables: ["adaptations"], contexts: ["learner", "supportPlan"], bulkGeneratable: true, scope: "LEARNER" },
  FICHE_ACCESSIBILITE_HANDICAP: { family: "ADMINISTRATIF", description: "Fiche accessibilité handicap.", maturity: "GENERIC", recommendedVariables: ["apprenant_nom", "besoin_accessibilite", "amenagements_prevus"], importantVariables: ["apprenant_nom"], optionalVariables: ["referent_handicap"], contexts: ["learner", "accessibility"], bulkGeneratable: true, scope: "LEARNER" },
  BILAN_FIN_PARCOURS: { family: "APRES_FORMATION", description: "Bilan fin de parcours.", maturity: "GENERIC", recommendedVariables: ["apprenant_nom", "formation_titre", "competences_acquises"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["suite_recommandee"], contexts: ["learner", "assessment"], bulkGeneratable: true, scope: "LEARNER" },
  PV_EVALUATION: { family: "APRES_FORMATION", description: "Procès-verbal d'évaluation.", maturity: "GENERIC", recommendedVariables: ["formation_titre", "session_dates", "decision"], importantVariables: ["formation_titre", "decision"], optionalVariables: ["jury_nom"], contexts: ["session", "assessment"], bulkGeneratable: false, scope: "SESSION" },
  BILAN_PEDAGOGIQUE_SESSION: { family: "APRES_FORMATION", description: "Bilan pédagogique de session.", maturity: "GENERIC", recommendedVariables: ["formation_titre", "session_dates", "objectifs_atteints"], importantVariables: ["formation_titre"], optionalVariables: ["ameliorations"], contexts: ["session", "quality"], bulkGeneratable: false, scope: "SESSION" },
  RAPPORT_QUALITE_SESSION: { family: "QUALIOPI", description: "Rapport qualité session.", maturity: "GENERIC", recommendedVariables: ["formation_titre", "indicateurs_qualite", "actions_correctives"], importantVariables: ["formation_titre"], optionalVariables: ["reclamations"], contexts: ["session", "quality"], bulkGeneratable: false, scope: "SESSION" },
  ATTESTATION_ASSIDUITE: { family: "APRES_FORMATION", description: "Attestation d'assiduité.", maturity: "PARTIAL", recommendedVariables: ["apprenant_nom", "formation_titre", "heures_prevues", "heures_realisees"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["taux_assiduite"], contexts: ["session", "learner", "attendance"], bulkGeneratable: true, scope: "LEARNER" },
  FICHE_RECLAMATION: { family: "QUALIOPI", description: "Fiche réclamation.", maturity: "GENERIC", recommendedVariables: ["reclamant_nom", "date_reclamation", "objet"], importantVariables: ["objet"], optionalVariables: ["reponse_apportee"], contexts: ["quality"], bulkGeneratable: false, scope: "SESSION" },
  ACTION_CORRECTIVE: { family: "QUALIOPI", description: "Fiche action corrective.", maturity: "GENERIC", recommendedVariables: ["probleme_identifie", "cause", "action_prevue"], importantVariables: ["probleme_identifie", "action_prevue"], optionalVariables: ["date_echeance"], contexts: ["quality"], bulkGeneratable: false, scope: "SESSION" },
  REGISTRE_AMELIORATION_CONTINUE: { family: "QUALIOPI", description: "Registre d'amélioration continue.", maturity: "GENERIC", recommendedVariables: ["periode", "actions_liste", "statuts"], importantVariables: ["actions_liste"], optionalVariables: ["responsables"], contexts: ["quality"], bulkGeneratable: false, scope: "ANNUAL" },
  AVOIR: { family: "FINANCE", description: "Avoir financier.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "client_nom", "avoir_numero", "montant"], importantVariables: ["client_nom", "montant"], optionalVariables: ["facture_origine"], contexts: ["billing"], bulkGeneratable: false, scope: "COMPANY" },
  RECU_PAIEMENT: { family: "FINANCE", description: "Reçu de paiement.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "client_nom", "montant_paye"], importantVariables: ["client_nom", "montant_paye"], optionalVariables: ["mode_paiement"], contexts: ["billing"], bulkGeneratable: false, scope: "COMPANY" },
  RELANCE_PAIEMENT: { family: "FINANCE", description: "Relance paiement.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "client_nom", "facture_numero", "montant_du"], importantVariables: ["client_nom", "montant_du"], optionalVariables: ["lien_paiement"], contexts: ["billing"], bulkGeneratable: false, scope: "COMPANY" },
  RELEVE_FINANCEMENTS: { family: "FINANCE", description: "Relevé des financements.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "financeurs_liste", "montants", "statuts"], importantVariables: ["financeurs_liste"], optionalVariables: ["commentaires_financement"], contexts: ["funding"], bulkGeneratable: false, scope: "COMPANY" },
  DOSSIER_OPCO_FINANCEUR: { family: "FINANCE", description: "Dossier OPCO ou financeur.", maturity: "PARTIAL", recommendedVariables: ["centre_nom", "financeur_nom", "formation_titre", "montant_demande"], importantVariables: ["financeur_nom", "formation_titre"], optionalVariables: ["pieces_jointes"], contexts: ["funding", "session"], bulkGeneratable: false, scope: "COMPANY" },
  JUSTIFICATIF_FINANCEUR: { family: "FINANCE", description: "Justificatif financeur.", maturity: "PARTIAL", recommendedVariables: ["apprenant_nom", "financeur_nom", "formation_titre", "heures_realisees"], importantVariables: ["apprenant_nom", "formation_titre"], optionalVariables: ["montant_finance"], contexts: ["funding", "learner"], bulkGeneratable: true, scope: "LEARNER" },
  TABLEAU_ANNUEL_QUALITE: { family: "QUALIOPI", description: "Tableau annuel qualité.", maturity: "GENERIC", recommendedVariables: ["annee", "indicateurs_liste", "taux_satisfaction"], importantVariables: ["annee"], optionalVariables: ["actions_amelioration"], contexts: ["quality", "annualReport"], bulkGeneratable: false, scope: "ANNUAL" },
  RAPPORT_ACTIVITE_CENTRE: { family: "ADMINISTRATIF", description: "Rapport d'activité centre.", maturity: "GENERIC", recommendedVariables: ["centre_nom", "annee", "nombre_sessions", "ca_total"], importantVariables: ["centre_nom", "annee"], optionalVariables: ["perspectives"], contexts: ["organization", "annualReport"], bulkGeneratable: false, scope: "ANNUAL" },
  CONVENTION_CONTRAT_BILAN: { family: "ADMINISTRATIF", description: "Convention ou contrat bilan de compétences.", maturity: "PARTIAL", recommendedVariables: ["beneficiaire_nom", "centre_nom", "dates_bilan", "prix_total"], importantVariables: ["beneficiaire_nom", "centre_nom"], optionalVariables: ["objectifs_bilan"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  FEUILLE_ROUTE_BENEFICIAIRE: { family: "ADMINISTRATIF", description: "Feuille de route bénéficiaire.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "objectif_initial", "etapes_bilan"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["travaux_personnels"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  BILAN_PHASE_PRELIMINAIRE: { family: "ADMINISTRATIF", description: "Phase préliminaire du bilan.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "situation_initiale", "objectifs_valides"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["attentes_bilan"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  BILAN_PHASE_INVESTIGATION: { family: "ADMINISTRATIF", description: "Phase investigation du bilan.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "competences_identifiees", "pistes_metiers"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["pistes_formation"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  BILAN_PHASE_CONCLUSION: { family: "ADMINISTRATIF", description: "Phase conclusion du bilan.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "projet_retenu", "plan_action"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["actions_3_mois"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  SYNTHESE_BILAN_COMPETENCES: { family: "ADMINISTRATIF", description: "Synthèse du bilan de compétences.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "projet_professionnel", "competences_cles"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["plan_action"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  PLAN_ACTION_3_6_MOIS: { family: "ADMINISTRATIF", description: "Plan d'action à 3-6 mois.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "objectif_final", "actions_liste"], importantVariables: ["beneficiaire_nom", "actions_liste"], optionalVariables: ["echeances"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  RESTITUTION_IKIGAI: { family: "ADMINISTRATIF", description: "Restitution Ikigai.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "synthese_ikigai", "pistes_a_explorer"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["ikigai_passion"], contexts: ["beneficiary", "bilan", "ikigai"], bulkGeneratable: false, scope: "LEARNER" },
  CARTOGRAPHIE_COMPETENCES: { family: "ADMINISTRATIF", description: "Cartographie des compétences.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "competences_liste", "competences_a_developper"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["preuves"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
  AUTORISATION_PARTAGE_DOSSIER: { family: "ADMINISTRATIF", description: "Autorisation de partage du dossier.", maturity: "PARTIAL", recommendedVariables: ["beneficiaire_nom", "destinataire_nom", "documents_partages"], importantVariables: ["beneficiaire_nom", "destinataire_nom"], optionalVariables: ["finalite_partage"], contexts: ["beneficiary", "sharing"], bulkGeneratable: false, scope: "LEARNER" },
  DOSSIER_NUMERIQUE_EXPORTABLE: { family: "ADMINISTRATIF", description: "Dossier numérique exportable.", maturity: "GENERIC", recommendedVariables: ["beneficiaire_nom", "artefacts_liste", "synthese_globale"], importantVariables: ["beneficiaire_nom"], optionalVariables: ["date_export"], contexts: ["beneficiary", "bilan"], bulkGeneratable: false, scope: "LEARNER" },
};

export const DOCUMENT_CATALOG = DOCUMENT_TYPES.map((d) => ({
  type: d.value,
  label: d.label,
  ...BASE[d.value],
})) satisfies DocumentCatalogEntry[];

export const DOCUMENT_CATALOG_BY_TYPE = Object.fromEntries(DOCUMENT_CATALOG.map((d) => [d.type, d])) as Record<string, DocumentCatalogEntry>;
