export const DOCUMENT_TYPES = [
  { value: "PROGRAMME_FORMATION", label: "Programme de formation", phase: "Catalogue" },
  { value: "PROGRAMME", label: "Programme de formation", phase: "Avant" },
  { value: "FICHE_FORMATION_PUBLIQUE", label: "Fiche formation publique", phase: "Catalogue" },
  { value: "OBJECTIFS_PEDAGOGIQUES", label: "Objectifs pédagogiques", phase: "Catalogue" },
  { value: "PREREQUIS_POSITIONNEMENT", label: "Pré-requis et positionnement", phase: "Catalogue" },
  { value: "DEROULE_PEDAGOGIQUE_MODULE", label: "Déroulé pédagogique par module", phase: "Catalogue" },
  { value: "GRILLE_FORMATION_COMPETENCES", label: "Grille formation ↔ compétences", phase: "Catalogue" },
  { value: "PLAN_INDIVIDUEL_FORMATION", label: "Plan individuel de formation", phase: "Catalogue" },
  { value: "CONVENTION_FORMATION_ENTREPRISE", label: "Convention de formation entreprise", phase: "Contractualisation" },
  { value: "CONTRAT_FORMATION_PARTICULIER", label: "Contrat de formation particulier", phase: "Contractualisation" },
  { value: "DEVIS_FORMATION", label: "Devis formation", phase: "Contractualisation" },
  { value: "BON_DE_COMMANDE", label: "Bon de commande", phase: "Contractualisation" },
  { value: "CGV_B2B", label: "CGV B2B", phase: "Contractualisation" },
  { value: "CGV_B2C", label: "CGV B2C", phase: "Contractualisation" },
  { value: "CONVOCATION_APPRENANT", label: "Convocation apprenant", phase: "Contractualisation" },
  { value: "CONVOCATION_FORMATEUR", label: "Convocation formateur", phase: "Contractualisation" },
  { value: "REGLEMENT_INTERIEUR", label: "Règlement intérieur", phase: "Contractualisation" },
  { value: "FEUILLE_EMARGEMENT", label: "Feuille d'émargement", phase: "Sessions & planning" },
  { value: "PLANNING_SESSION", label: "Planning de session", phase: "Sessions & planning" },
  { value: "PLANNING_FORMATEUR", label: "Planning formateur", phase: "Sessions & planning" },
  { value: "ORDRE_MISSION_FORMATEUR", label: "Ordre de mission formateur", phase: "Sessions & planning" },
  { value: "FICHE_INTERVENTION_FORMATEUR", label: "Fiche d'intervention formateur", phase: "Sessions & planning" },
  { value: "RELEVE_ASSIDUITE", label: "Relevé d'assiduité", phase: "Sessions & planning" },
  { value: "FICHE_INCIDENT_SESSION", label: "Fiche incident session", phase: "Sessions & planning" },
  { value: "DEMANDE_MODIFICATION_PLANNING", label: "Demande modification planning", phase: "Sessions & planning" },
  { value: "SYNTHESE_DISPONIBILITES_FORMATEURS", label: "Synthèse disponibilités formateurs", phase: "Sessions & planning" },
  { value: "FICHE_APPRENANT", label: "Fiche apprenant", phase: "Suivi apprenant" },
  { value: "GRILLE_EVALUATION_INITIALE", label: "Grille d'évaluation initiale", phase: "Suivi apprenant" },
  { value: "GRILLE_EVALUATION_CONTINUE", label: "Grille d'évaluation continue", phase: "Suivi apprenant" },
  { value: "COMPTE_RENDU_PROGRESSION", label: "Compte rendu progression", phase: "Suivi apprenant" },
  { value: "PLAN_ACCOMPAGNEMENT_INDIVIDUALISE", label: "Plan d'accompagnement individualisé", phase: "Suivi apprenant" },
  { value: "FICHE_ACCESSIBILITE_HANDICAP", label: "Fiche accessibilité handicap", phase: "Suivi apprenant" },
  { value: "BILAN_FIN_PARCOURS", label: "Bilan fin de parcours", phase: "Suivi apprenant" },
  { value: "PV_EVALUATION", label: "Procès-verbal d'évaluation", phase: "Clôture & qualité" },
  { value: "BILAN_PEDAGOGIQUE_SESSION", label: "Bilan pédagogique de session", phase: "Clôture & qualité" },
  { value: "RAPPORT_QUALITE_SESSION", label: "Rapport qualité session", phase: "Clôture & qualité" },
  { value: "ATTESTATION_ASSIDUITE", label: "Attestation d'assiduité", phase: "Clôture & qualité" },
  { value: "FICHE_RECLAMATION", label: "Fiche réclamation", phase: "Clôture & qualité" },
  { value: "ACTION_CORRECTIVE", label: "Fiche action corrective", phase: "Clôture & qualité" },
  { value: "REGISTRE_AMELIORATION_CONTINUE", label: "Registre d'amélioration continue", phase: "Clôture & qualité" },
  { value: "AVOIR", label: "Avoir", phase: "Administratif & finance" },
  { value: "RECU_PAIEMENT", label: "Reçu de paiement", phase: "Administratif & finance" },
  { value: "RELANCE_PAIEMENT", label: "Relance paiement", phase: "Administratif & finance" },
  { value: "RELEVE_FINANCEMENTS", label: "Relevé financements", phase: "Administratif & finance" },
  { value: "DOSSIER_OPCO_FINANCEUR", label: "Dossier OPCO / financeur", phase: "Administratif & finance" },
  { value: "JUSTIFICATIF_FINANCEUR", label: "Justificatif financeur", phase: "Administratif & finance" },
  { value: "TABLEAU_ANNUEL_QUALITE", label: "Tableau annuel qualité", phase: "Administratif & finance" },
  { value: "RAPPORT_ACTIVITE_CENTRE", label: "Rapport activité centre", phase: "Administratif & finance" },
  { value: "CONVENTION_CONTRAT_BILAN", label: "Convention / contrat bilan", phase: "Bilan de compétences" },
  { value: "FEUILLE_ROUTE_BENEFICIAIRE", label: "Feuille de route bénéficiaire", phase: "Bilan de compétences" },
  { value: "BILAN_PHASE_PRELIMINAIRE", label: "Phase préliminaire", phase: "Bilan de compétences" },
  { value: "BILAN_PHASE_INVESTIGATION", label: "Phase investigation", phase: "Bilan de compétences" },
  { value: "BILAN_PHASE_CONCLUSION", label: "Phase conclusion", phase: "Bilan de compétences" },
  { value: "SYNTHESE_BILAN_COMPETENCES", label: "Synthèse bilan de compétences", phase: "Bilan de compétences" },
  { value: "PLAN_ACTION_3_6_MOIS", label: "Plan d'action 3-6 mois", phase: "Bilan de compétences" },
  { value: "RESTITUTION_IKIGAI", label: "Restitution Ikigai", phase: "Bilan de compétences" },
  { value: "CARTOGRAPHIE_COMPETENCES", label: "Cartographie compétences", phase: "Bilan de compétences" },
  { value: "AUTORISATION_PARTAGE_DOSSIER", label: "Autorisation partage dossier", phase: "Bilan de compétences" },
  { value: "DOSSIER_NUMERIQUE_EXPORTABLE", label: "Dossier numérique exportable", phase: "Bilan de compétences" },
  { value: "CONVENTION", label: "Convention de formation", phase: "Avant" },
  { value: "CONTRAT_FORMATION", label: "Contrat de formation", phase: "Avant" },
  { value: "LIVRET_ACCUEIL", label: "Livret d'accueil", phase: "Avant" },
  { value: "TEST_POSITIONNEMENT", label: "Test de positionnement", phase: "Avant" },
  { value: "CONVOCATION", label: "Convocation", phase: "Avant" },
  { value: "EMARGEMENT", label: "Feuille d'émargement", phase: "Pendant" },
  { value: "SUPPORT_COURS", label: "Support de cours", phase: "Pendant" },
  { value: "QUESTIONNAIRE_SUIVI", label: "Questionnaire de suivi", phase: "Pendant" },
  { value: "ATTESTATION", label: "Attestation de fin de formation", phase: "Après" },
  { value: "CERTIFICAT", label: "Certificat de réalisation", phase: "Après" },
  { value: "ATTESTATION_PRESENCE", label: "Attestation de présence / assiduité", phase: "Après" },
  { value: "QUESTIONNAIRE_SATISFACTION", label: "Questionnaire de satisfaction", phase: "Après" },
  { value: "ENQUETE_SATISFACTION_CHAUD", label: "Enquête satisfaction à chaud", phase: "Après" },
  { value: "ENQUETE_SATISFACTION_FROID", label: "Enquête satisfaction à froid", phase: "Après" },
  { value: "SYNTHESE_SATISFACTION", label: "Synthèse satisfaction", phase: "Après" },
  { value: "DIPLOME_TITRE", label: "Diplôme ou titre certifiant", phase: "Après" },
  { value: "DEVIS", label: "Devis", phase: "Comptable" },
  { value: "FACTURE", label: "Facture", phase: "Comptable" },
  { value: "BPF", label: "Bilan pédagogique et financier", phase: "Annuel" },
] as const;

export const GENERATABLE_DOCUMENT_TYPES = DOCUMENT_TYPES.map((d) => d.value);

export const DOC_LABELS = Object.fromEntries(DOCUMENT_TYPES.map((d) => [d.value, d.label])) as Record<string, string>;

export const PER_LEARNER_DOCUMENT_TYPES = [
  "CONVOCATION_APPRENANT",
  "CONTRAT_FORMATION_PARTICULIER",
  "PLAN_INDIVIDUEL_FORMATION",
  "PREREQUIS_POSITIONNEMENT",
  "CONVOCATION",
  "ATTESTATION",
  "CERTIFICAT",
  "ATTESTATION_PRESENCE",
  "ATTESTATION_ASSIDUITE",
  "RELEVE_ASSIDUITE",
  "JUSTIFICATIF_FINANCEUR",
  "FICHE_APPRENANT",
  "GRILLE_EVALUATION_INITIALE",
  "GRILLE_EVALUATION_CONTINUE",
  "COMPTE_RENDU_PROGRESSION",
  "PLAN_ACCOMPAGNEMENT_INDIVIDUALISE",
  "FICHE_ACCESSIBILITE_HANDICAP",
  "BILAN_FIN_PARCOURS",
  "TEST_POSITIONNEMENT",
  "QUESTIONNAIRE_SUIVI",
  "QUESTIONNAIRE_SATISFACTION",
  "ENQUETE_SATISFACTION_CHAUD",
  "ENQUETE_SATISFACTION_FROID",
] as const;
