export const VERIFICATION_STATUSES = ["VERIFIED", "NEEDS_VERIFICATION"] as const;

export const SKILL_CONFIDENCE_LEVELS = [
  "CONFIRMED",
  "SELF_REPORTED",
  "OBSERVED",
  "INFERRED",
  "UNKNOWN",
] as const;

export const CAPABILITIES = [
  "SOURCE_CANDIDATE",
  "ASSESS_CANDIDATE",
  "REFER_TO_SERVICE",
  "ACKNOWLEDGE_REFERRAL",
  "PRESCRIBE_IMMERSION",
  "HOST_IMMERSION",
  "PROVIDE_JOB",
  "PROVIDE_CDD",
  "PROVIDE_CDI",
  "PROVIDE_ALTERNANCE",
  "PROVIDE_FEEDBACK",
  "ASSESS_PREREQUISITES",
  "DELIVER_TRAINING",
  "CERTIFY_SKILL",
  "FINANCE_TRAINING",
  "FINANCE_MOBILITY",
  "SUPPORT_MOBILITY",
  "SUPPORT_CHILDCARE",
  "SUPPORT_HOUSING",
  "SUPPORT_DISABILITY",
  "PROVIDE_SOCIAL_SUPPORT",
  "PROVIDE_EQUIPMENT",
  "COACH_CANDIDATE",
  "BUY_PROGRAM",
  "FOLLOW_UP",
  "REPORT_OUTCOME",
] as const;

export const ACTOR_TYPES = [
  "ORCHESTRATOR",
  "PRESCRIBER",
  "BUYER",
  "FUNDER",
  "EMPLOYER",
  "HOST_COMPANY",
  "PROFESSIONAL_ORGANIZATION",
  "TRAINING_CENTER",
  "CFA",
  "OPCO",
  "SIAE",
  "GEIQ",
  "MOBILITY_PARTNER",
  "CHILDCARE_PARTNER",
  "DISABILITY_PARTNER",
  "HOUSING_PARTNER",
  "SOCIAL_PARTNER",
  "LOCAL_AUTHORITY",
  "TERRITORIAL_COORDINATOR",
] as const;

export const OPPORTUNITY_TYPES = [
  "JOB",
  "CDI",
  "CDD",
  "ALTERNANCE",
  "TRAINING",
  "PMSMP",
  "GEIQ",
  "SIAE",
  "ETTI",
  "POEI",
  "OTHER",
] as const;

export const NEED_TYPES = [
  "SKILL_GAP",
  "LANGUAGE",
  "MOBILITY",
  "CHILDCARE",
  "EQUIPMENT",
  "FUNDING",
  "EXPERIENCE",
  "PREREQUISITE",
  "AVAILABILITY",
  "POSTURE",
  "HOUSING",
  "DISABILITY_SUPPORT",
  "SOCIAL_SUPPORT",
  "OTHER",
] as const;

export const PATHWAY_STATUSES = [
  "DRAFT",
  "AWAITING_HUMAN_APPROVAL",
  "ACTIVE",
  "BLOCKED",
  "COMPLETED",
  "CANCELLED",
  "SUPERSEDED",
] as const;

export const PATHWAY_STEP_STATUSES = [
  "DRAFT",
  "READY",
  "ASSIGNED",
  "SENT",
  "ACKNOWLEDGED",
  "ACCEPTED",
  "IN_PROGRESS",
  "COMPLETED",
  "REJECTED",
  "BLOCKED",
  "NO_RESPONSE",
  "CANCELLED",
] as const;

export const PATHWAY_STEP_TYPES = [
  "DIAGNOSTIC",
  "PROJECT_VALIDATION",
  "LBR_ACTION",
  "REFERRAL",
  "SERVICE",
  "TRAINING",
  "MOBILITY",
  "IMMERSION",
  "INTERVIEW",
  "OPPORTUNITY",
  "FUNDING",
  "OUTCOME",
  "MILESTONE",
] as const;

export const REFERRAL_STATUSES = [
  "DRAFT",
  "SENT",
  "ACKNOWLEDGED",
  "ACCEPTED",
  "IN_PROGRESS",
  "COMPLETED",
  "REJECTED",
  "NO_RESPONSE",
  "CANCELLED",
] as const;

export const COST_CATEGORIES = [
  "LBR_ACCOMPANIMENT",
  "TRAINING",
  "MOBILITY",
  "CHILDCARE",
  "EQUIPMENT",
  "PSYCHOLOGICAL_SUPPORT",
  "ADMINISTRATION",
  "IMMERSION",
  "OTHER",
] as const;

export const FUNDING_STATUSES = [
  "NOT_STARTED",
  "REQUESTED",
  "UNDER_REVIEW",
  "APPROVED",
  "PARTIALLY_APPROVED",
  "REJECTED",
  "PAID",
  "CANCELLED",
] as const;

export const OUTCOME_TYPES = [
  "CDI",
  "CDD",
  "ALTERNANCE",
  "TRAINING",
  "GEIQ",
  "SIAE",
  "ETTI",
  "OTHER_ACTIVE",
  "PATHWAY_CONTINUES",
  "NO_ACTIVE_OUTCOME",
] as const;

export const OUTCOME_MILESTONES = ["J7", "J30", "J60", "J90"] as const;

export const MILESTONE_STATUSES = ["NOT_DUE", "PENDING", "ACTIVE", "INACTIVE", "UNKNOWN"] as const;

export const NEED_CAPABILITY_MAP = {
  SKILL_GAP: "DELIVER_TRAINING",
  LANGUAGE: "DELIVER_TRAINING",
  MOBILITY: "SUPPORT_MOBILITY",
  CHILDCARE: "SUPPORT_CHILDCARE",
  EQUIPMENT: "PROVIDE_EQUIPMENT",
  FUNDING: "FINANCE_TRAINING",
  EXPERIENCE: "HOST_IMMERSION",
  PREREQUISITE: "ASSESS_PREREQUISITES",
  AVAILABILITY: "COACH_CANDIDATE",
  POSTURE: "COACH_CANDIDATE",
  HOUSING: "SUPPORT_HOUSING",
  DISABILITY_SUPPORT: "SUPPORT_DISABILITY",
  SOCIAL_SUPPORT: "PROVIDE_SOCIAL_SUPPORT",
  OTHER: "REFER_TO_SERVICE",
} as const satisfies Record<(typeof NEED_TYPES)[number], (typeof CAPABILITIES)[number]>;
