ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PROGRAMME_FORMATION';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'FICHE_FORMATION_PUBLIQUE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'OBJECTIFS_PEDAGOGIQUES';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PREREQUIS_POSITIONNEMENT';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'DEROULE_PEDAGOGIQUE_MODULE';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'GRILLE_FORMATION_COMPETENCES';
ALTER TYPE "DocumentType" ADD VALUE IF NOT EXISTS 'PLAN_INDIVIDUEL_FORMATION';
